//#include "lib/MathTools/BasicToolSet.h"
#include "lib/MathTools/BooleanAlgebra.h"
#include "lib/MathTools/AdvancedTools/ScientificToolSet.h"
#include "lib/MathTools/AdvancedTools/LinearAlgebra.h"
#include "lib/DatafileTools/connectfile.h"
#include "lib/StringTools.h"